//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyProduct("Nelibur Framework")]
[assembly: System.Reflection.AssemblyCopyright("Copyright © Sergey Morenko. Since 2014")]
[assembly: System.Reflection.AssemblyTrademark("Nelibur Framework")]
[assembly: System.Reflection.AssemblyConfiguration("Release")]
[assembly: System.Reflection.AssemblyVersion("0.0.0.0")]
[assembly: System.Reflection.AssemblyFileVersion("0.0.0.0")]
[assembly: System.Reflection.AssemblyInformationalVersion("Compiled By Serjo")]


